Feature/improve url handling
zicht/url-bundle pull request #18
Opened 2017-06-21 06:42 UTC by boudewijn-zicht

2017-06-21 07:22 UTC, muhammedeminakbulut requested changes
Zou je de test kunnen herschrijven naar de drie eenheid //arrange //act //assert dat maakt het ook wat leesbaarder. Het is nu moeilijk te begrijpen wat er gebeurt

2017-06-21 07:22 UTC, muhammedeminakbulut commented on tests/ZichtTest/Bundle/UrlBundle/Aliasing/ListenerTest.php
> +            new UrlAlias('/foo', '/bar', $statusCode)
Je test hier ook de UrlAlias mee, dat is niet de bedoeling. je kan die ook prima mocken.

2017-06-21 07:22 UTC, muhammedeminakbulut commented on tests/ZichtTest/Bundle/UrlBundle/Aliasing/ListenerTest.php
> +        if ($expectsException) {
ik snap heel de if else constructie niet. (bad smell) en je zou als je een exception wilt testen toch liever de bestaande PHPunit dingen kunnen gebruiken https://phpunit.de/manual/current/en/writing-tests-for-phpunit.html#writing-tests-for-phpunit.exceptions

2017-06-21 07:22 UTC, muhammedeminakbulut commented on src/Zicht/Bundle/UrlBundle/Aliasing/Listener.php
> +                        $event->setResponse(new RedirectResponse($redirectUrl, $url->getMode()));
eigenlijk ben je hier helemaal klaar met deze functie toch? Waarom stappen we er niet gelijk uit hier? Als er later door iemand onderaan wat word toegevoegd kan dat vervelend zijn. (defensive programming)

2017-07-31 08:32 UTC, boudewijn-zicht commented
In overleg met @muhammedeminakbulut stellen we het refactoren van de unit tests uit, zie issue https://zichtonline.atlassian.net/browse/ZICHTDEV-637

2017-07-31 08:33 UTC, merged