fix for scheduled content
zicht/url-bundle pull request #21
Opened 2017-06-28 15:20 UTC by pbergman

cleanup of code and support to provide attributes when creating a alias

2017-06-28 15:36 UTC, muhammedeminakbulut requested changes
het gaat me vooral om de visibilities wat daar de reden achter is. de rest is meer comment.

2017-06-28 15:36 UTC, muhammedeminakbulut commented on src/Zicht/Bundle/UrlBundle/Aliasing/Aliaser.php
> +    protected $conflictingPublicUrlStrategy = Aliasing::STRATEGY_SUFFIX;
wat is de reden dat deze een protected visibility krijgen?

2017-06-28 15:36 UTC, muhammedeminakbulut commented on src/Zicht/Bundle/UrlBundle/Aliasing/Doctrine/CreateAliasSubscriber.php
> +    protected function addRecord($entity, array $action = [])
waarom heeft dit een protected visibility?

2017-06-28 15:36 UTC, muhammedeminakbulut commented on src/Zicht/Bundle/UrlBundle/Aliasing/Doctrine/CreateAliasSubscriber.php
> +            if (false !== ($index = array_search($entity, array_column($this->records, 0), true))) {
waarom is dit beter dan ` $this->records[spl_object_hash($e->getEntity())] = $e->getEntity();`
zo een key access lijkt me sneller dan het doorzoeken van een array? of vergis ik me?

2017-06-28 15:44 UTC, pbergman commented on src/Zicht/Bundle/UrlBundle/Aliasing/Doctrine/CreateAliasSubscriber.php
> +    protected function addRecord($entity, array $action = [])
consistency, vond het maar niks dat er protected en private door elkaar werden gebruikt en zag geen reden voor private (en geloof dat we afgesproken hadden dat voor bundels we protected zouden gebruiken zodat het extendable is)

2017-06-28 15:51 UTC, pbergman commented on src/Zicht/Bundle/UrlBundle/Aliasing/Doctrine/CreateAliasSubscriber.php
> +            if (false !== ($index = array_search($entity, array_column($this->records, 0), true))) {
los van dat het nu meer in de array stop en die logica niet meer werkt, kan ik me niet zo goed een voorstelling maken waarom dat sneller zou moeten zijn (en of je dat zou merken). Ken de 
internals ook niet zo goed maar zover ik weet moet hij zowel bij een key index of een searh bij allebij door de array lopen om te kijken of iets bestaat. Maar zou zeggen testen is weten.

2017-06-30 06:30 UTC, boudewijn-zicht approved these changes

2017-06-30 06:30 UTC, boudewijn-zicht commented on src/Zicht/Bundle/UrlBundle/Aliasing/Aliaser.php
> +    protected $conflictingPublicUrlStrategy = Aliasing::STRATEGY_SUFFIX;
Waarschijnlijk om consistent te zijn met de bovenstaande properties die ook protected zijn

2017-07-03 07:02 UTC, muhammedeminakbulut approved these changes

2017-07-03 07:03 UTC, muhammedeminakbulut commented
@pbergman jenkins kan de tests niet draaien kan je daar naar kijken.

2017-08-01 14:48 UTC, merged