Fix PHPCS and tests
zicht/url-bundle pull request #44
Opened 2018-10-29 14:59 UTC by erik-zicht

Major changes needed for phpunit

2018-10-29 15:01 UTC, erik-zicht commented
retest this please

2018-10-29 15:12 UTC, erik-zicht commented
retest this please

2018-10-29 15:17 UTC, erik-zicht commented
retest this please

2018-10-30 16:18 UTC, erik-zicht commented
retest this please

2018-10-30 16:19 UTC, erik-zicht commented
retest this please

2018-10-31 14:35 UTC, 7ochem requested changes

2018-10-31 14:35 UTC, 7ochem commented on composer.json
>          "psr-0": { "": ["src/", "tests/"] }
Graag `tests` in `autoload-dev` section zetten, anders worden alle tests ook meegenomen in de classmap van een project bij autoloader optimization.
```
    "autoload": {
        "psr-0": { "": ["src/"] }
    },
    "autoload-dev": {
        "psr-0": { "": ["tests/"] }
    },
```

2018-11-05 16:09 UTC, 7ochem requested changes

2018-11-05 16:09 UTC, 7ochem commented on composer.json
> +            "phpcbf -s src/Zicht/ tests/ZichtTest/ --standard=vendor/zicht/standards-php/Zicht --extensions=php --parallel=$(nproc)"
Je lint fix bevat wel `test/ZichtTest/`, maar lint zelf niet

2018-11-12 12:08 UTC, 7ochem approved these changes

2018-11-12 12:12 UTC, boudewijn-zicht approved these changes

2018-11-12 12:13 UTC, merged