Generate fragment for missing static refs to prevent error page
zicht/url-bundle pull request #51
Opened 2019-06-13 10:43 UTC by 7ochem

Generate a URL fragment, like `#static_reference:name`, for missing static refs to be more friendly and prevent a 404 error because a URL like www.example.com/[static_reference:%20name] is not found.

When `$params` are passed in, these will be placed after the fragment. According to the [URI RFC](https://tools.ietf.org/html/rfc3986) the fragment starts at `#` until the end of the URI (and thus can contain `?`, `&`, `=` etc.). When a static ref is missing and `$params` are passed in, this will result in `#static_reference:name?param1=value1&param2=value2` instead of `/[static_reference:%20name]?param1=value1&param2=value2`, which I still consider an improvement.

Targetting 2.x branch with the intention to push this change up to 3.x and 4.x branches after merge.

2019-06-13 11:35 UTC, 7ochem commented
Retest this please

2019-06-13 11:55 UTC, 7ochem commented
The linting test fails because Composer is running out of it's 1.5Gb memory during install with no lock file. Seems that this version 2.x branch has too many dependencies. Previous PR nr 50 targetting the 4.x branch did run a successful linting test...

2019-06-17 14:34 UTC, erik-zicht commented
So if you click on a non-existing static-reference, you have a refresh to the same page? Is this really an improvement? I'm not sure, a 404 is still what's going on, a static-ref could not be found.

2019-06-17 14:42 UTC, 7ochem commented
> So if you click on a non-existing static-reference, you have a refresh to the same page?
No refresh, it's a fragment, not available as an element with the same ID in the DOM, so probably nothing will happen except that the fragment will be added to the address in the address bar

> a 404 is still what's going on, a static-ref could not be found.
It should be noticeable for/noted towards the dev team, not something to bother the user with (throwing an error page in his face).

2019-06-21 12:03 UTC, pknijff commented
Leaving the code as it is just now doesn't make sense either. So basically a 404 gets thrown just to show that the `static_ref` doesn't exist? For us developers it makes sense but for the actual visitor it doesn't. In the last case it shouldn't behave like this. This is not a solution to the problem that a `static_ref` doesn't exist, this change is just a more elegant/silent way to show that is not working as expected.

2019-06-21 12:04 UTC, peerknife approved these changes

2019-06-26 07:18 UTC, erik-zicht commented
I'm not convinced that "hiding" the error is better. Now the user clicks, and nothing happens, as if this is intended. Also, there is no error triggered anywhere, nobody knows that there is a problem. I just don't think this is better :slightly_smiling_face:

2019-07-01 07:23 UTC, boudewijn-zicht requested changes
I agree with @erik-zicht.  The solution is to ensure that each static-ref is set.  My favorite way of ensuring this is to have a script run at deploy that adds static refs when needed. See https://github.com/zicht/ticket-trigger-culture/blob/release/1.5.x/src/Zicht/Bundle/TicketTriggerCultureBundle/Command/StaticRefsCommand.php

2019-07-01 07:28 UTC, 7ochem commented
> I agree with @erik-zicht. The solution is to ensure that each static-ref is set. My favorite way of ensuring this is to have a script run at deploy that adds static refs when needed. See https://github.com/zicht/ticket-trigger-culture/blob/release/1.5.x/src/Zicht/Bundle/TicketTriggerCultureBundle/Command/StaticRefsCommand.php

Ok, this looks quite nice. And you add it to the deployment tasks I assume. This could solve our issue I guess. But half of the times we would still insert `#link_to_content_page` refs as the customer needs to create content pages for some static refs first.

Could we include (an abstract for) this command in the bundle? I'm not a big fan of copy-pasting a solution into every project. Better to have some code in the bundle to facilitate this and to have to do the minimal in your project to get it running.

2019-07-01 07:37 UTC, boudewijn-zicht commented
> Ok, this looks quite nice. And you add it to the deployment tasks I assume. This could solve our issue I guess. But half of the times we would still insert `#link_to_content_page` refs as the customer needs to create content pages for some static refs first.

Correct.

> Could we include (an abstract for) this command in the bundle? I'm not a big fan of copy-pasting a solution into every project. Better to have some code in the bundle to facilitate this and to have to do the minimal in your project to get it running.

Sure, feel free to make a simple prefab command.  I would suggest one that is very simple, i.e. it just iterates over an `['static_ref' => ['nl' => '//nl/foo', 'en' => '//en/foo']]` array.

2019-07-04 09:57 UTC, pknijff commented
> I agree with @erik-zicht. The solution is to ensure that each static-ref is set. My favorite way of ensuring this is to have a script run at deploy that adds static refs when needed. See https://github.com/zicht/ticket-trigger-culture/blob/release/1.5.x/src/Zicht/Bundle/TicketTriggerCultureBundle/Command/StaticRefsCommand.php

I agree with you guys as well, in the end it doesn't really matter if it shows an error or not (arguable). Making sure the `static_ref` exists during deployment makes more sense. Way to go guys, could this be closed now?

2019-07-04 10:21 UTC, 7ochem commented
> Sure, feel free to make a simple prefab command. I would suggest one that is very simple, i.e. it just iterates over an ['static_ref' => ['nl' => '//nl/foo', 'en' => '//en/foo']] array.

I don't want prefab, that's still copy-paste. I meant something like a trait or a service that you can use to pass the array to.

Closing this PR with the intent to create a new PR for was has been suggested

2019-07-04 10:21 UTC, closed without merging