Custom headers through annotations
zicht/url-bundle pull request #52
Opened 2019-07-19 15:07 UTC by erik-zicht

2019-07-22 07:06 UTC, wtfzdotnet reviewed
Ik vraag me ergens af hoeveel dit nu toevoegd, een controller method kan je immers ook herschrijven om niet gebruik te maken van de @Template annotaties en kan je dus zelf gewoon een response terug geven. 

Daarnaast vraag ik me af of het wel wenselijk is dat waardes expliciet alleen geset worden wanneer de header nog niet bestaat, ik zou eigenlijk verwachten dat dit altijd headers vervangt

2019-07-22 07:06 UTC, wtfzdotnet commented on src/Zicht/Bundle/UrlBundle/Aliasing/Listener.php
> +            foreach ($this->customHeaders as $header => $value) {
Denk een andere plek geschikter zou zijn

2019-07-22 07:06 UTC, wtfzdotnet commented on src/Zicht/Bundle/UrlBundle/Aliasing/Listener.php
> +
Wat betere error output tijdens dev is wel zo handig :octopus:

2019-07-24 07:51 UTC, 7ochem requested changes
> Ik vraag me ergens af hoeveel dit nu toevoegd, een controller method kan je immers ook herschrijven om niet gebruik te maken van de @template annotaties en kan je dus zelf gewoon een response terug geven.

Hilarisch genoeg, wordt het gebruik van `@Template` afgeraden, ook omdat je anders geen consistente return type hebt bij een mogelijke redirect response en dus als je geen `@Template` zou gebruiken, zou je heel gemakkelijk headers toe kunnen voegen aan je response: `$response->headers->set('X-Robots-Tag','noindex');`. Zie sensiolabs/SensioFrameworkExtraBundle#610 :wink: 

Gaan we nu niet iets over engineren? Krijgen we hier geen last van in een later stadium? Bijv. incompatibiliteit met "vanilla" Symfony?

Wat doe je overigens met de Header annotation in het geval van mogelijke redirect responses, bijv. `if (x) { return new RedirectResponse(....); }` en als niet `x` dan wordt er een template gerendered. Wordt dan in beide gevallen de header meegegeven?

Ook kun je geen variabelen/constanten gebruiken: `$response->headers->set('Content-Type', self::CONTENT_TYPE);`

Al met al lijken me de use-cases waarin je dit daadwerkelijk kunt gebruiken vrij minimaal, maar is er wel een listener die elke request een reflection gaat uitvoeren.

2019-07-24 07:51 UTC, 7ochem commented on src/Zicht/Bundle/UrlBundle/Aliasing/Listener.php
> +    public function onKernelController(Event\FilterControllerEvent $event)
Als je deze functionaliteit wilt toevoegen, vind ik dat je hiervoor een aparte listener service moet aanmaken. Je gaat nu header annotations uitlezen in een listener die aliases toepast. Dat vind ik niet logisch

2019-07-24 08:03 UTC, erik-zicht commented
Ik denk ook dat er te weinig usecases zijn. Ik zie nog geen manier om dit in-te-pluggen zonder listener (+overhead).

2019-07-24 08:03 UTC, closed without merging