Rename hasInternalAlias and hasPublicAlias
zicht/url-bundle pull request #8
Opened 2017-02-13 15:20 UTC by DoNormal

Fix for issue #7.

2017-02-14 08:30 UTC, muhammedeminakbulut requested changes
kan je ook de jenkins job nalopen. en de return types goed checken :D

2017-02-28 09:20 UTC, muhammedeminakbulut commented
The build is failing

2017-02-28 09:20 UTC, muhammedeminakbulut commented on src/Zicht/Bundle/UrlBundle/Aliasing/Aliasing.php
>       * @return null
ok

2017-02-28 09:20 UTC, muhammedeminakbulut commented on src/Zicht/Bundle/UrlBundle/Aliasing/Aliasing.php
> +     * @return null|string|UrlAlias
ok

2017-05-11 09:10 UTC, boudewijn-zicht requested changes
Ik denk dat we hiermee een andere kant op moeten, de `has... ` methoden moeten idd wel deprecated worden, maar niet vervangen met 'get...' methoden.

Het verwarrende hier is dat de methodes dezelfde database entity teruggeven, hierin zit zowel de internal als de external alias.  

Het verschil in de methods zit alleen in het selectie criteria, i.e. select alias entity by publicAlias or by internalAlias.  In beide gevallen krijg je een alias entity uit de database.

Dus veel liever twee nieuwe methodes: `getAliasByInternalUrl` en `getAliasByPublicUrl`.  Die hebben dan geen `$asObject` argument meer nodig.  Beide methoden geven `null` of een `UrlAlias` instance terug.  De instance bied dan toegang tot zowel de `getInternalUrl` als de `getPublicUrl` van de alias.

2017-05-26 09:27 UTC, closed without merging